# Functional Programming
- **Lambda**
- **map**
- **Filter**
- these all are anonymous functions,we create


# Lambda Syntax :lambda argument:expressions

In [1]:
x= lambda a,b:a+b
print(x(2,3))

5


# Map Syntax:map(function,iterable1,iterable2,..)

In [21]:
l1=[1,2,3,4,5,6]
l=map(lambda x:x*x,l1)
l2=map(lambda x:x**3,range(10))
print(list(l))
print(list(l2))


[1, 4, 9, 16, 25, 36]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


In [19]:
m = list(map(str, input().split()))
k=map(lambda x:x.upper(),m)
print(list(k))

sita ram


TypeError: descriptor 'upper' of 'str' object needs an argument

In [14]:
p=map(str,input().split())
print(p)

sita ram


In [16]:
x = list(map(str, input().split()))
print(x)

sita ravi ram
['sita', 'ravi', 'ram']


# Filter

In [24]:
l=list(filter(lambda x:x>5,range(11)))
print(l)

[6, 7, 8, 9, 10]


# Numpy
- Numerical Python
- used to create arrays(general and random)
- 2 dimentional arrays
- scientific computation
- import numpy
- comprised of math and random
- array is a sub module in numpy used to create array

In [31]:
import numpy as np
print(dir(np),end=' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [27]:
ar=np.array("I am here".split())
print(ar) #row matix

['I' 'am' 'here']


In [41]:
ar=np.array([(i,i+1,i+2) for i in range(1,11)])
print(ar)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]]


In [39]:
ar=np.array({i for i in range(1,11)})
print(ar)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [42]:
l=np.array([(1,2),(93,4)])
print(l)


[[ 1  2]
 [93  4]]


In [44]:
r=np.array(range(10))
print(r)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
r=np.array(range(10,30))
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


# Creating Arrayusing arange() method
- range()-python
- arrange()-numpy
- arrange(lw,up,step)--inclusive

In [51]:
import numpy as np
s=np.arange(10)
print(s)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
s=np.arange(10,45,5)
print(s)

[10 15 20 25 30 35 40]


# Creating array with arange().reshape()
- row matrix 2d array using reshape()
- based on the size of array
- numpy.arrange(30).reshape(1,30)#row matrix
- (95,60),(2,23),(31,67)# column matrix

In [53]:
l=np.arange(30).reshape(-1,6)
print(l)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


# Random
- grnerates a random values in a range
    - random.randint() generates a random value
        - random.randint(,)
        - random.randint(,,)
        - random.randint(,())
    - random.random(())
    - random.rand(,)
    - random.randn(,)

In [55]:
r=np.random.randint(10)
print(r)
l=np.random.randint(10,40)
print(l)
k=np.random.randint(10,50,6)
print(list(k))
m=np.random.randint(10,100,(2,4))
print(m)
j=np.random.randint(10,50,12).reshape(3,4)
print(j)

9
17
[29, 32, 42, 47, 12, 22]
[[97 38 85 82]
 [89 43 57 46]]
[[14 41 13 13]
 [24 36 32 41]
 [21 28 37 41]]


In [56]:
rn=np.random.random((2,4))
print(rn)

[[0.38059462 0.34496459 0.48299912 0.94559566]
 [0.2289247  0.91132455 0.48307827 0.13485503]]


In [57]:
rd=np.random.rand(3,2)
print(rd)

[[0.14942811 0.4214212 ]
 [0.15916593 0.47391278]
 [0.68105912 0.27078717]]


# Linspace

In [66]:
# linspace
print(np.linspace(10,20,5))
print(np.linspace(3,9,4))

[10. 12. 14. 16. 18. 20.]
[3. 5. 7. 9.]


# Zeros and Ones

In [67]:
o=np.ones((5,4)) #5 coloumns and 4 rows
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [71]:
o=np.zeros((5,4)) #5 coloumns and 4 rows
print(o)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Fill and Full

In [72]:
f=np.full((2,3),"clg")
print(f)
fa=np.full((2,3),5)
print(fa)
o.fill(10)
print(o)

[['clg' 'clg' 'clg']
 ['clg' 'clg' 'clg']]
[[5 5 5]
 [5 5 5]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [80]:
st=np.array([['hi','hello','puppy'],[9,12,34],[1.2,9.3,8.5]])
print(st)
print(type(st))
print(st.dtype)
print(np.diag(st))
print(np.diag([1,2,3,4]))
print(np.eye(3))
print(np.eye(4))

[['hi' 'hello' 'puppy']
 ['9' '12' '34']
 ['1.2' '9.3' '8.5']]
<class 'numpy.ndarray'>
<U5
['hi' '12' '8.5']
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Slicing
- ar[:] lw,up
- ar[row:col]
- ar[row][index]

In [105]:
arr=np.arange(1,26).reshape(-1,5)
print(arr)
print(arr[2][2])
print(arr[3:5,1:4])
print(arr[:2])
print(arr[3:])
print(arr[:5,1:])
print(arr[3:,:2])
print(arr[:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13
[[17 18 19]
 [22 23 24]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[16 17 18 19 20]
 [21 22 23 24 25]]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
[[16 17]
 [21 22]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [106]:
m=np.random.randint(30,60,(5,5))
print(m)

[[47 54 54 44 33]
 [45 54 39 57 43]
 [59 37 37 51 40]
 [35 30 33 50 56]
 [59 56 55 49 51]]


In [107]:
print(arr+m)
print("...............................")
print(arr-m)
print("...............................")
print(arr*m)
print("...............................")
print(m/arr)
print("...............................")
print(m//arr)
print("...............................")
print(np.min(m))
print("...............................")
print(np.max(m))

[[48 56 57 48 38]
 [51 61 47 66 53]
 [70 49 50 65 55]
 [51 47 51 69 76]
 [80 78 78 73 76]]
...............................
[[-46 -52 -51 -40 -28]
 [-39 -47 -31 -48 -33]
 [-48 -25 -24 -37 -25]
 [-19 -13 -15 -31 -36]
 [-38 -34 -32 -25 -26]]
...............................
[[  47  108  162  176  165]
 [ 270  378  312  513  430]
 [ 649  444  481  714  600]
 [ 560  510  594  950 1120]
 [1239 1232 1265 1176 1275]]
...............................
[[47.         27.         18.         11.          6.6       ]
 [ 7.5         7.71428571  4.875       6.33333333  4.3       ]
 [ 5.36363636  3.08333333  2.84615385  3.64285714  2.66666667]
 [ 2.1875      1.76470588  1.83333333  2.63157895  2.8       ]
 [ 2.80952381  2.54545455  2.39130435  2.04166667  2.04      ]]
...............................
[[47 27 18 11  6]
 [ 7  7  4  6  4]
 [ 5  3  2  3  2]
 [ 2  1  1  2  2]
 [ 2  2  2  2  2]]
...............................
30
...............................
59


In [109]:
print(np.mean(m))
print(np.std(m))
print(np.median(ar))
print(arr.dot(m))

46.72
8.879279250029251
6.5
[[ 749  673  650  756  718]
 [1974 1828 1740 2011 1833]
 [3199 2983 2830 3266 2948]
 [4424 4138 3920 4521 4063]
 [5649 5293 5010 5776 5178]]


# Broadcasting

In [112]:
print(arr+5)
print("...............................")
print(arr*2)
print("...............................")
print(arr/2)

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
...............................
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
...............................
[[ 0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]]


# Logorithm and Exponentials

In [113]:
np.log(0)

<ipython-input-113-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [114]:
np.log(1)

0.0

In [117]:
print(np.log(2))
print(np.log2(2))
print(np.log([1,2,3]))

0.6931471805599453
1.0
[0.         0.69314718 1.09861229]


In [120]:
print(np.exp(3))
print(np.exp(0.6931471805599453))

20.085536923187668
2.0


In [125]:
def greater(a,b):
    if a>b:
        return a
    else:
        return b
v=np.vectorize(greater([1,2,33],[1,2,3]))


TypeError: 'vectorize' object is not iterable

# Pandas
- Means Paneldata
- One of the data science package
- Used for data manipulation,analysis and cleaning
- Contains mainly two data structures in it
    - 1.Series
    - 2.Dataframes
- Sequence of data
- Data frame is data with row  and column


In [126]:
import pandas as pd
pd.__version__

'1.1.3'

# Series 
- **Syntax:pd.Series(data,index,dtype)**

In [128]:
s='hello'
pd.Series(s)

0    hello
dtype: object

In [132]:
s1='hi  hi hello good morning'.split()
pd.Series(s1)

0         hi
1         hi
2      hello
3       good
4    morning
dtype: object

In [134]:
pd.Series(s1,index=[1,2,3,4,5])

1         hi
2         hi
3      hello
4       good
5    morning
dtype: object

In [136]:
pd.Series(s1,index={1,1,2,3,4,5,2,3,4})

1         hi
2         hi
3      hello
4       good
5    morning
dtype: object

In [138]:
l1=[12,'name',4.567]
pd.Series(l1,index={'int','str','float'})

float       12
int       name
str      4.567
dtype: object

In [139]:
t=('a','e','i','o','u')
pd.Series(t,index=('v1','v2','v3','v4','v5'))

v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [144]:
m={1:'23',2:'45',3:'67','name':'sowmya'}
pd.Series(m,index=m)

1           23
2           45
3           67
name    sowmya
dtype: object

# DataFrames

In [146]:
st='clear man not understand'.split()
pd.DataFrame(st)

0
0       clear
1         man
2         not
3  understand

In [150]:
l=[[1,2,3],[6,4,2]]
pd.DataFrame(l,index=['list1','list2'])

0  1  2
list1  1  2  3
list2  6  4  2

In [162]:
m={1:'23',2:'45',3:'67','name':'sowmya'}
pd.DataFrame(m,index=[1,2])

1   2   3    name
1  23  45  67  sowmya
2  23  45  67  sowmya

In [165]:
d={'Names':["Krishna",'Mahesh','Ram'],'Marks':[45,23,78]}
pd.DataFrame(d,index=['S1','S2','S3'])

Names  Marks
S1  Krishna     45
S2   Mahesh     23
S3      Ram     78

In [166]:
d={'key1':('a','y','r'),'key2':(6,4,2)}
pd.DataFrame(d,index=[1,2,3])

key1  key2
1    a     6
2    y     4
3    r     2

In [168]:
s=pd.Series(np.random.randint(20,40,8))
print(s)

0    20
1    22
2    29
3    31
4    36
5    20
6    30
7    26
dtype: int32


In [170]:
s[3:]

3    31
4    36
5    20
6    30
7    26
dtype: int32

In [174]:
s[1:10:3]

1    22
4    36
7    26
dtype: int32

# Data Analysis and Manipulation

In [184]:
df=pd.DataFrame({'month':[2,3,4,5,6],'days':[23,34,67,89,23]},index=[2001,2009,2003,2020,2332])
df

month  days
2001      2    23
2009      3    34
2003      4    67
2020      5    89
2332      6    23

n_p  n_h
2001    2   23
2009    3   34
2003    4   67
2020    5   89
2345    6   23

In [218]:
df.join(df1)

month  days  n_p   n_h
2001      2    23  2.0  23.0
2009      3    34  3.0  34.0
2003      4    67  4.0  67.0
2020      5    89  5.0  89.0
2332      6    23  NaN   NaN

In [219]:
df1.join(df)

n_p  n_h  month  days
2001    2   23    2.0  23.0
2009    3   34    3.0  34.0
2003    4   67    4.0  67.0
2020    5   89    5.0  89.0
2345    6   23    NaN   NaN

In [220]:
df3=pd.DataFrame({'a':[2,3,4,5,6],'b':[23,34,67,89,23]},index=[2001,2009,2003,2020,2345])
df3

a   b
2001  2  23
2009  3  34
2003  4  67
2020  5  89
2345  6  23

In [221]:
df4=pd.DataFrame({'a':[2,3,4,5,6],'b':[23,34,67,89,23]},index=[2001,2009,2003,20210,23145])
df4

a   b
2001   2  23
2009   3  34
2003   4  67
20210  5  89
23145  6  23

In [222]:
con=pd.concat([df3,df4])
con

a   b
2001   2  23
2009   3  34
2003   4  67
2020   5  89
2345   6  23
2001   2  23
2009   3  34
2003   4  67
20210  5  89
23145  6  23

In [223]:
con=pd.concat([df,df1])
con

month  days  n_p   n_h
2001    2.0  23.0  NaN   NaN
2009    3.0  34.0  NaN   NaN
2003    4.0  67.0  NaN   NaN
2020    5.0  89.0  NaN   NaN
2332    6.0  23.0  NaN   NaN
2001    NaN   NaN  2.0  23.0
2009    NaN   NaN  3.0  34.0
2003    NaN   NaN  4.0  67.0
2020    NaN   NaN  5.0  89.0
2345    NaN   NaN  6.0  23.0

In [224]:
ma_df=pd.read_csv('marks.csv')
ma_df

name  maths  science  english  physics
0    A     23     45.0       64     35.0
1    B     23     32.0       32     65.0
2    C     27     78.0       78     45.0
3    D     56     78.0       43     89.0
4    e     65     76.0       96     45.0
5    F     46      NaN       23      NaN

In [225]:
ma_df.head()

name  maths  science  english  physics
0    A     23     45.0       64     35.0
1    B     23     32.0       32     65.0
2    C     27     78.0       78     45.0
3    D     56     78.0       43     89.0
4    e     65     76.0       96     45.0

In [226]:
ma_df.tail()

name  maths  science  english  physics
1    B     23     32.0       32     65.0
2    C     27     78.0       78     45.0
3    D     56     78.0       43     89.0
4    e     65     76.0       96     45.0
5    F     46      NaN       23      NaN

In [227]:
ma_df.tail(4)

name  maths  science  english  physics
2    C     27     78.0       78     45.0
3    D     56     78.0       43     89.0
4    e     65     76.0       96     45.0
5    F     46      NaN       23      NaN

In [228]:
ma_df.head(2)

name  maths  science  english  physics
0    A     23     45.0       64     35.0
1    B     23     32.0       32     65.0

In [229]:
pd.read_csv('marks.csv',header=None)

0      1        2        3        4
0  name  maths  science  english  physics
1     A     23       45       64       35
2     B     23       32       32       65
3     C     27       78       78       45
4     D     56       78       43       89
5     e     65       76       96       45
6     F     46      NaN       23      NaN

In [230]:
pd.read_csv('marks.csv',usecols=['name','english'])

name  english
0    A       64
1    B       32
2    C       78
3    D       43
4    e       96
5    F       23

In [231]:
d=pd.read_csv('marks.csv',names=['N','M','S','E'])
d

N        M        S        E
name  maths  science  english  physics
A        23       45       64       35
B        23       32       32       65
C        27       78       78       45
D        56       78       43       89
e        65       76       96       45
F        46      NaN       23      NaN

In [234]:
d['S']

name    english
A            64
B            32
C            78
D            43
e            96
F            23
Name: S, dtype: object

In [235]:
ma_df.columns

Index(['name', 'maths', 'science', 'english', 'physics'], dtype='object')

In [236]:
ma_df.describe()

maths    science   english    physics
count   6.000000   5.000000   6.00000   5.000000
mean   40.000000  61.800000  56.00000  55.800000
std    18.242807  21.776134  28.22056  21.522082
min    23.000000  32.000000  23.00000  35.000000
25%    24.000000  45.000000  34.75000  45.000000
50%    36.500000  76.000000  53.50000  45.000000
75%    53.500000  78.000000  74.50000  65.000000
max    65.000000  78.000000  96.00000  89.000000

In [238]:
ma_df.dtypes

name        object
maths        int64
science    float64
english      int64
physics    float64
dtype: object

In [239]:
ma_df.index

RangeIndex(start=0, stop=6, step=1)

In [240]:
ma_df.shape

(6, 5)

In [241]:
ma_df.shape[1]

5

In [242]:
ma_df.shape[0]

6

In [253]:
ma_df.sort_values('maths')

name  maths  science  english  physics college
0    A     23     45.0       64     35.0     abc
1    B     23     32.0       32     65.0     abc
2    C     27     78.0       78     45.0     abc
5    F     46      NaN       23      NaN     abc
3    D     56     78.0       43     89.0     abc
4    e     65     76.0       96     45.0     abc

In [254]:
ma_df.sort_values('maths',ascending=False)

name  maths  science  english  physics college
4    e     65     76.0       96     45.0     abc
3    D     56     78.0       43     89.0     abc
5    F     46      NaN       23      NaN     abc
2    C     27     78.0       78     45.0     abc
0    A     23     45.0       64     35.0     abc
1    B     23     32.0       32     65.0     abc

In [255]:
ma_df['college']='abc'

In [256]:
ma_df


name  maths  science  english  physics college
0    A     23     45.0       64     35.0     abc
1    B     23     32.0       32     65.0     abc
2    C     27     78.0       78     45.0     abc
3    D     56     78.0       43     89.0     abc
4    e     65     76.0       96     45.0     abc
5    F     46      NaN       23      NaN     abc

In [257]:
ma_df.sample(3)

name  maths  science  english  physics college
5    F     46      NaN       23      NaN     abc
4    e     65     76.0       96     45.0     abc
0    A     23     45.0       64     35.0     abc

In [258]:
ma_df.maths.value_counts()

23    2
46    1
27    1
65    1
56    1
Name: maths, dtype: int64

In [259]:
ma_df.isnull()

name  maths  science  english  physics  college
0  False  False    False    False    False    False
1  False  False    False    False    False    False
2  False  False    False    False    False    False
3  False  False    False    False    False    False
4  False  False    False    False    False    False
5  False  False     True    False     True    False

In [260]:
ma_df.isna()

name  maths  science  english  physics  college
0  False  False    False    False    False    False
1  False  False    False    False    False    False
2  False  False    False    False    False    False
3  False  False    False    False    False    False
4  False  False    False    False    False    False
5  False  False     True    False     True    False

In [261]:
ma_df.dropna

<bound method DataFrame.dropna of   name  maths  science  english  physics college
0    A     23     45.0       64     35.0     abc
1    B     23     32.0       32     65.0     abc
2    C     27     78.0       78     45.0     abc
3    D     56     78.0       43     89.0     abc
4    e     65     76.0       96     45.0     abc
5    F     46      NaN       23      NaN     abc>